const fs=require('fs');const path=require('path');const BASE_URL='https://raw.githubusercontent.com/maroAlmeida/news-vc/main/assets/';async function fetchJSON(url){const response=await fetch(url);if(!response.ok)throw new Error(`Erro ao buscar ${url}: ${response.status}`);return response.json()}
async function fetchText(url){const response=await fetch(url);if(!response.ok)throw new Error(`Erro ao buscar ${url}: ${response.status}`);return response.text()}
function generateImageCell(item,link){const imgTag=`<img width="110" height="110" alt="{item-tit}" title="{item-tit}"src="{item-img}" style="width:110px;height:110px;max-height:110px;max-width:110px;display:block;margin:auto;object-fit:cover;border:0;outline:none;text-decoration:none;"/>`;let inner=imgTag;if(item.img_link===!0&&link!==undefined&&link!==null&&link!=='false'){inner=`<a href="${link}" style="mso-line-height-rule:exactly;text-decoration:none;display:block">${imgTag}</a>`}
return `<td height="110px" valign="top" width="110px" align="left" style="padding:0;Margin:0">\n  ${inner}\n<\/td>`}
function renderItens(template,itens,colorConfig,ctas){return itens.map(item=>{let bloco=template;const imageCellRegex=/<td height="110px" valign="top" width="110px" align="left" style="padding:0;Margin:0">\s*<img[^>]*\/>\s*<\/td>/;const match=bloco.match(imageCellRegex);if(match){const newImageCell=generateImageCell(item,item.link);bloco=bloco.replace(match[0],newImageCell)}
bloco=bloco.replace(/{item-img}/g,item.img||'');bloco=bloco.replace(/{item-tit}/g,item.tit||'');bloco=bloco.replace(/{item-txt}/g,item.txt||'');const ctaKey=(item.cta&&item.cta!=='false')?item.cta:null;const hasValidCta=ctaKey&&ctas[ctaKey]&&ctas[ctaKey]!=='';if(hasValidCta){bloco=bloco.replace(/{item-link}/g,item.link||'#');bloco=bloco.replace(/{item-cta}/g,ctas[ctaKey])}else{bloco=bloco.replace(/<!-- CTA:start -->([\s\S]*?)<!-- CTA:end -->/g,'')}
bloco=bloco.replace(/{tema-tit-color}/g,colorConfig.titColor);bloco=bloco.replace(/{tema-txt-color}/g,colorConfig.txtColor);return bloco}).join('')}
function generateBannerBlock(banner){if(!banner)return'';const{img,tit,link}=banner;const hasLink=(link&&link!=='false');const imgTag=`<img src="${img}" title="${tit}" alt="${tit}" width="100%" style="display:block;font-size:14px;border:0;outline:none;text-decoration:none;margin:0;height:auto;width:100%;max-width:600px;" />`;if(hasLink){return `<td bgcolor="#fff" align="center" style="padding:0;Margin:0;margin:0;background-color:#fff;width:100%;max-width:600px;overflow:hidden"><a href="${link}" style="mso-line-height-rule:exactly;text-decoration:none;display:block;">${imgTag}</a></td>`}else{return `<td bgcolor="#fff" align="center" style="padding:0;Margin:0;margin:0;background-color:#fff;width:100%;max-width:600px;overflow:hidden">${imgTag}</td>`}}(async()=>{try{const dataFilePath=process.argv[2]||'./data.json';if(!fs.existsSync(dataFilePath)){throw new Error(`Arquivo ${dataFilePath} não encontrado.`)}
const data=JSON.parse(fs.readFileSync(dataFilePath,'utf-8'));if(!data.vigencia){throw new Error('Campo "vigencia" não encontrado no data.json')}
if(data.versao===undefined){console.warn('⚠️ Campo "versao" não encontrado no data.json, usando padrão 1');data.versao=1}
const[colors,ctas,editorias,htmlTemplate]=await Promise.all([fetchJSON(`${BASE_URL}colors.json`),fetchJSON(`${BASE_URL}ctas.json`),fetchJSON(`${BASE_URL}editorias.json`),fetchText(`${BASE_URL}template.html`)]);let html=htmlTemplate;const bannerBlock=generateBannerBlock(data.banner);html=html.replace('{banner-block}',bannerBlock);const temaRegex=/<!-- LOOP:temas:start -->([\s\S]*?)<!-- LOOP:temas:end -->/;const temaMatch=html.match(temaRegex);if(!temaMatch)throw new Error('❌ LOOP:temas não encontrado no HTML');const temaTemplate=temaMatch[1];const temasRenderizados=Object.entries(data).filter(([key,tema])=>tema&&tema.items&&!['banner','vigencia','versao'].includes(key)).map(([temaKey,tema])=>{let blocoTema=temaTemplate;const colorConfig=colors[tema.color]||{bgColor:'#ffffff',titColor:'#000000',txtColor:'#000000'};const abaImg=editorias[tema.aba]||'';blocoTema=blocoTema.replace(/{tema-nome}/g,temaKey);blocoTema=blocoTema.replace(/{tema-aba}/g,abaImg);blocoTema=blocoTema.replace(/{tema-bg}/g,colorConfig.bgColor);const itensRegex=/<!-- LOOP:itens:start -->([\s\S]*?)<!-- LOOP:itens:end -->/;const itensMatch=blocoTema.match(itensRegex);if(!itensMatch)return blocoTema;const itemTemplate=itensMatch[1];const itensHtml=renderItens(itemTemplate,tema.items||[],colorConfig,ctas);blocoTema=blocoTema.replace(itensRegex,itensHtml);return blocoTema}).join('');html=html.replace(temaRegex,temasRenderizados);const outputFileName=`NewsPraVoce-DPSP-${data.vigencia}_v${data.versao}.html`;const outputDir=path.dirname(dataFilePath);const outputFile=path.join(outputDir,outputFileName);fs.writeFileSync(outputFile,html);console.log(`✅ Build concluído! Arquivo gerado: ${outputFile}`)}catch(error){console.error('❌ Erro no build:',error.message);process.exit(1)}})()